master-data
fiskaltrust/getting-started pull request #22
Opened 2021-09-15 10:31 UTC by fabry-training

changed graphic
explanations in the intro
added test options

2021-09-16 07:50 UTC, fiscoal requested changes

2021-09-16 07:50 UTC, fiscoal commented on posdealers/03-sales/04c-masterdata-creation.md
> +Mit dem Anlegen oder dem Import der Daten der KassenBetreiber(#Firmendaten-bereit-stellen) werden die Benutzerdaten festgelegt. Bei der Erstanmeldung der Benutzer dient die E-Mailadresse als Benutzer
Falls wegen Ausdruck, würd ich die ganze Klammer entfernen. Ansonsten würds ich wieder verlinken.

2021-09-16 07:50 UTC, fiscoal commented on posdealers/03-sales/04c-masterdata-creation.md
> +!Stammdaten(media/fiskaltrustAgencies.png "Agenturen")
Broken image

```suggestion
![Stammdaten](media/fiskaltrustAgencies.png "Agenturen")
```

2021-09-16 07:50 UTC, fiscoal commented on posdealers/03-sales/04c-masterdata-creation.md
> +!Standorte(media/fiskaltrustStandorte.png "Standorte")
Broken image

```suggestion
![Standorte](media/fiskaltrustStandorte.png "Standorte")
```

2021-09-16 07:50 UTC, fiscoal commented on posdealers/03-sales/04c-masterdata-creation.md
> +!POSSystem(media/fiskaltrustPOS-System.png "Ansicht POSSystem für KasenHersteller")
Broken image

```suggestion
![POSSystem](media/fiskaltrustPOS-System.png "Ansicht POSSystem für KasenHersteller")
```

2021-09-20 10:01 UTC, fabry-training commented on posdealers/03-sales/04c-masterdata-creation.md
> +Mit dem Anlegen oder dem Import der Daten der KassenBetreiber(#Firmendaten-bereit-stellen) werden die Benutzerdaten festgelegt. Bei der Erstanmeldung der Benutzer dient die E-Mailadresse als Benutzer
der Link sollte funktionieren, habe es getestet im VSC und im Browser.

2021-09-20 10:12 UTC, fabry-training commented on posdealers/03-sales/04c-masterdata-creation.md
> +Mit dem Anlegen oder dem Import der Daten der KassenBetreiber(#Firmendaten-bereit-stellen) werden die Benutzerdaten festgelegt. Bei der Erstanmeldung der Benutzer dient die E-Mailadresse als Benutzer
```suggestion
Mit dem [Anlegen oder dem Import der Daten der KassenBetreiber](#Firmendaten-bereit-stellen) werden die Benutzerdaten festgelegt. Bei der Erstanmeldung der Benutzer dient die E-Mailadresse als Benutzername, ein Passwort wird vom KassenBetreiber selbst vergeben.
```

2021-09-20 10:15 UTC, merged